### ISSUE TITLE
Recent update broke meal consumption

### ISSUE THREAD

**Issue by SolariusScorch** [RimWorld-CCL-Reborn/AlienRaces#36] opened 2020-05-25 14:34 UTC
First of all, many thanks for this wonderful mod/tool! It makes the (Rim)world better and brighter.
Ad meritum: after a recent update a few days ago, my pawns stopped eating. I couldn't interact with meals, right-clicking them did not even open the context menu (eat, pick up, etc.). However, they could still feed animals.
Perhaps it's some mod conflict, but using the Humanoid Alien Races version from the 8th of May works just fine. It's the update from the 19th of May which is causing the issue.
I will be happy to provide any further info you might need.
best regards,
Solar

**Comment by erdelf** [comment] 2020-05-25 14:37
well, a log would be the absolute minimum.. what races you are using, relevant other mods etc.

**Comment by SolariusScorch** [comment] 2020-05-25 17:32
I started a new colony with only these mods enabled:
- Harmony
- Core
- Humanoid Alien Races 2.0

The problem persists.
Attached is the log:
[Player.log](https://github.com/RimWorld-CCL-Reborn/AlienRaces/files/4678284/Player.log)
and the save (zipped to appease GitHub):
[No_Eat.zip](https://github.com/RimWorld-CCL-Reborn/AlienRaces/files/4678286/No_Eat.zip)
I hope it helps!
Solar

**Comment by maestroBR** [comment] 2020-05-29 15:52
it's happening to me too

**Comment by erdelf** [comment] 2020-06-01 12:33
Huh, legit didn't know you could get rimworld on gog.
Anyway, issue should be fixed by the commit on may 29th.

**Comment by SolariusScorch** [comment] 2020-06-05 17:32
Awesome, thank you!
Do you think it's worthwhile to update?

**Comment by erdelf** [comment] 2020-06-05 17:54
I mean, do you want your people to eat ?

**Comment by SolariusScorch** [comment] 2020-06-08 21:03
I meant, upgrade from the older version from a month ago... :)

**Comment by Davi-DeGanne** [comment] 2020-10-05 04:43
I can reproduce this issue with 100% reliability with this modlist:

Harmony
Core
Mod Manager
Humanoid Alien Races 2.0 (latest master branch)

Here are the repro steps:
1. Start a colony with the crashlanded scenario
2. Wait until a colonist gets hungry (but do not let them eat yet)
3. Use debug mode to spawn and immediately kill a tribal warrior
4. Draft and undraft hungry colonist. They will not eat, and you will get a NullReferenceException in the log.
5. Use debug mode to destroy the tribal warrior's corpse
6. Draft and undraft colonist. They will now eat again, as normal.

(Incidentally, this means that the workaround for this until it is fixed, is to destroy all your human(oid?) corpses, whether via the debug menu, or other means.)

**Comment by erdelf** [comment] 2020-10-05 14:13
Correct, the current master branch will have that issue due to a so-far unresolved issue, working on fixing that.
Steam is on an older version though.

**Closed as completed** 2021-08-22 22:36 UTC
